// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqekxwhywrcnfwotlbdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxZWt4d2h5d3JjbmZ3b3RsYmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzI4MzgsImV4cCI6MjA2MTUwODgzOH0.S1WSn97mozNfe2zh2dzVNd0OD31B8AtUWs0egLYTrCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);